import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import SiteHeader from "@/components/header/SiteHeader";
import { ThemeProvider } from "next-themes";
import SiteFooter from "@/components/footer/SiteFooter";

export const metadata: Metadata = {
  title: "Support Center",
  description: "Open Source Support Center Generated by Exworth",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SiteHeader />
          <main className="mt-16" style={{ minHeight: "calc(100vh - 8rem)" }}>
            {children}
          </main>
          <SiteFooter />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
